defaults:
  - model_checkpoint
  - early_stopping
  - model_summary
  - rich_progress_bar
  - _self_

model_checkpoint:
  dirpath: ${paths.output_dir}/checkpoints
  filename: "epoch_{epoch:03d}"
  monitor: "valid wer"
  mode: "min"
  save_last: True
  auto_insert_metric_name: False

early_stopping:
  monitor: "valid wer"
  patience: 1000
  mode: "min"

model_summary:
  max_depth: -1
